# Generated by Django 5.1.15 on 2026-02-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
    ]
