# Generated by Django 5.1.15 on 2026-02-03 00:26

import django.db.models.deletion
import production_ledger.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "episode_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("ops", "Ops"),
                            ("ethics", "Ethics"),
                            ("other", "Other"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("target_minutes", models.PositiveIntegerField(default=45)),
                (
                    "recording_context",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("in_person", "In Person"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="remote",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("scheduled", "Scheduled"),
                            ("recorded", "Recorded"),
                            ("ingested", "Ingested"),
                            ("transcribed", "Transcribed"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                (
                    "live_notes",
                    models.TextField(
                        blank=True, help_text="Notes captured during recording"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode",
                "verbose_name_plural": "Episodes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("questions", "Questions"),
                            ("show_notes", "Show Notes"),
                            ("segment_suggestions", "Segment Suggestions"),
                            ("social_posts", "Social Posts"),
                            ("titles", "Titles"),
                            ("chapters", "Chapters"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "input_prompt",
                    models.TextField(help_text="The prompt sent to the AI"),
                ),
                (
                    "input_context_refs",
                    models.JSONField(
                        default=dict,
                        help_text="References to input data: transcript_id, clip_ids, etc.",
                    ),
                ),
                ("output_text", models.TextField(help_text="The AI-generated output")),
                (
                    "provider",
                    models.CharField(help_text="AI provider name", max_length=50),
                ),
                (
                    "model",
                    models.CharField(help_text="Model identifier", max_length=100),
                ),
                (
                    "params",
                    models.JSONField(
                        default=dict, help_text="Parameters: temperature, etc."
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transparency_summary",
                    models.CharField(
                        blank=True,
                        help_text="Short label shown in UI for transparency",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Reviewer notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_artifacts",
                        to="production_ledger.episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Artifact",
                "verbose_name_plural": "AI Artifacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EpisodeRoleOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("host", "Host"),
                            ("producer", "Producer"),
                            ("editor", "Editor"),
                            ("guest", "Guest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_overrides",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_role_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode Role Override",
                "verbose_name_plural": "Episode Role Overrides",
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "export_type",
                    models.CharField(
                        help_text="Type of export: json, markdown, csv, html",
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_records",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Record",
                "verbose_name_plural": "Export Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "title",
                    models.CharField(blank=True, help_text="Job title", max_length=255),
                ),
                (
                    "org",
                    models.CharField(
                        blank=True, help_text="Organization", max_length=255
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "links",
                    models.JSONField(
                        blank=True, default=dict, help_text="Social/web links as JSON"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, help_text="e.g., America/Los_Angeles", max_length=50
                    ),
                ),
                ("consent_audio", models.BooleanField(default=False)),
                ("consent_video", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest",
                "verbose_name_plural": "Guests",
            },
        ),
        migrations.CreateModel(
            name="EpisodeGuest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("panelist", "Panelist"),
                            ("cohost", "Co-Host"),
                        ],
                        default="guest",
                        max_length=20,
                    ),
                ),
                (
                    "prep_notes",
                    models.TextField(
                        blank=True, help_text="Preparation notes for this guest"
                    ),
                ),
                (
                    "key_topics",
                    models.TextField(
                        blank=True, help_text="Key topics to cover with this guest"
                    ),
                ),
                (
                    "no_go_topics",
                    models.TextField(blank=True, help_text="Topics to avoid"),
                ),
                (
                    "quote_approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_guests",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_appearances",
                        to="production_ledger.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode Guest",
                "verbose_name_plural": "Episode Guests",
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("audio", "Audio"), ("video", "Video")], max_length=20
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("external_link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=production_ledger.models.media_upload_path,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("filename", models.CharField(blank=True, max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ingestion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "ingested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingested_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True)),
                ("timebox_minutes", models.PositiveIntegerField(default=5)),
                (
                    "owner_role",
                    models.CharField(
                        choices=[("host", "Host"), ("producer", "Producer")],
                        default="host",
                        max_length=20,
                    ),
                ),
                (
                    "bullet_prompts",
                    models.TextField(
                        blank=True, help_text="Bullet points for this segment"
                    ),
                ),
                (
                    "key_questions",
                    models.TextField(blank=True, help_text="Key questions to cover"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment",
                "verbose_name_plural": "Segments",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "brand_primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code, e.g. #FF5733",
                        max_length=7,
                    ),
                ),
                (
                    "default_intro_text",
                    models.TextField(
                        blank=True, help_text="Default intro text for episodes"
                    ),
                ),
                (
                    "default_outro_text",
                    models.TextField(
                        blank=True, help_text="Default outro text for episodes"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Show",
                "verbose_name_plural": "Shows",
            },
        ),
        migrations.AddField(
            model_name="episode",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="production_ledger.show",
            ),
        ),
        migrations.CreateModel(
            name="ShowNoteDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "markdown",
                    models.TextField(help_text="Show notes in Markdown format"),
                ),
                (
                    "chapters_json",
                    models.JSONField(
                        blank=True, help_text="Chapter markers as JSON", null=True
                    ),
                ),
                (
                    "resources_json",
                    models.JSONField(
                        blank=True, help_text="Resources/links as JSON", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_ai_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="show_note_drafts",
                        to="production_ledger.aiartifact",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_note_drafts",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Show Note Draft",
                "verbose_name_plural": "Show Note Drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShowNoteFinal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "markdown",
                    models.TextField(help_text="Final show notes in Markdown format"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_show_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_note_final",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "source_draft",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_versions",
                        to="production_ledger.shownotedraft",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Show Note Final",
                "verbose_name_plural": "Show Notes Final",
            },
        ),
        migrations.CreateModel(
            name="ShowRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("host", "Host"),
                            ("producer", "Producer"),
                            ("editor", "Editor"),
                            ("guest", "Guest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="production_ledger.show",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Show Role Assignment",
                "verbose_name_plural": "Show Role Assignments",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("upload", "Upload"), ("paste", "Paste")],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("txt", "Plain Text"),
                            ("vtt", "WebVTT"),
                            ("srt", "SubRip"),
                        ],
                        default="txt",
                        max_length=10,
                    ),
                ),
                ("raw_text", models.TextField(help_text="Raw transcript text")),
                (
                    "normalized_json",
                    models.JSONField(
                        blank=True,
                        help_text="Normalized JSON with speaker blocks and timestamps",
                        null=True,
                    ),
                ),
                (
                    "confidence_overall",
                    models.FloatField(
                        blank=True, help_text="Overall confidence score 0-1", null=True
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_media_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcripts",
                        to="production_ledger.mediaasset",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "ingested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingested_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript",
                "verbose_name_plural": "Transcripts",
                "ordering": ["-revision"],
            },
        ),
        migrations.CreateModel(
            name="ClipMoment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_ms",
                    models.PositiveIntegerField(help_text="Start time in milliseconds"),
                ),
                (
                    "end_ms",
                    models.PositiveIntegerField(help_text="End time in milliseconds"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "hook",
                    models.CharField(
                        blank=True, help_text="Hook/teaser text", max_length=500
                    ),
                ),
                (
                    "caption_draft",
                    models.TextField(blank=True, help_text="Draft caption for social"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tags"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                        ],
                        default="silver",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clip_moments",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clip_moments",
                        to="production_ledger.transcript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip Moment",
                "verbose_name_plural": "Clip Moments",
                "ordering": ["start_ms"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=True)),
                ("is_done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_checklist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="production_ledger.episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Item",
                "verbose_name_plural": "Checklist Items",
                "ordering": ["sort_order"],
                "indexes": [
                    models.Index(
                        fields=["organization_uuid", "episode"],
                        name="production__organiz_be8487_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aiartifact",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_f36499_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiartifact",
            index=models.Index(
                fields=["organization_uuid", "artifact_type"],
                name="production__organiz_ef13d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiartifact",
            index=models.Index(
                fields=["organization_uuid", "approval_status"],
                name="production__organiz_a371ab_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episoderoleoverride",
            unique_together={("episode", "user")},
        ),
        migrations.AddIndex(
            model_name="exportrecord",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_57e927_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(
                fields=["organization_uuid", "name"],
                name="production__organiz_5f85ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episodeguest",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_13fe48_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episodeguest",
            unique_together={("episode", "guest")},
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_130798_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["organization_uuid", "checksum_sha256"],
                name="production__organiz_7490ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_3c1f1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="show",
            index=models.Index(
                fields=["organization_uuid", "slug"],
                name="production__organiz_349a4f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="show",
            unique_together={("organization_uuid", "slug")},
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["organization_uuid", "show"],
                name="production__organiz_1b6718_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["organization_uuid", "status"],
                name="production__organiz_b8e5d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["organization_uuid", "scheduled_for"],
                name="production__organiz_3773c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shownotedraft",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_bc077c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shownotefinal",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_c472ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="showroleassignment",
            index=models.Index(
                fields=["show", "role"], name="production__show_id_79cab8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="showroleassignment",
            index=models.Index(
                fields=["user", "role"], name="production__user_id_8c8ae6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="showroleassignment",
            unique_together={("show", "user")},
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_d38158_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clipmoment",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="production__organiz_d964e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clipmoment",
            index=models.Index(
                fields=["organization_uuid", "priority"],
                name="production__organiz_50125a_idx",
            ),
        ),
    ]
