# Generated by Django 5.1.15 on 2026-02-03 21:40

from django.db import migrations, models


def _has_column(schema_editor, table_name, column_name):
    """Database-agnostic column existence check."""
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return any(col.name == column_name for col in description)


def add_guest_contact_fields(apps, schema_editor):
    """Add email and phone columns only if they don't already exist."""
    table_name = "production_ledger_guest"

    with schema_editor.connection.cursor() as cursor:
        if not _has_column(schema_editor, table_name, "email"):
            cursor.execute(
                "ALTER TABLE production_ledger_guest "
                "ADD COLUMN email varchar(254) NOT NULL DEFAULT ''"
            )

        if not _has_column(schema_editor, table_name, "phone"):
            cursor.execute(
                "ALTER TABLE production_ledger_guest "
                "ADD COLUMN phone varchar(50) NOT NULL DEFAULT ''"
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0002_add_episode_type_model"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_guest_contact_fields, reverse_code=noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="guest",
                    name="email",
                    field=models.EmailField(blank=True, max_length=254),
                ),
                migrations.AddField(
                    model_name="guest",
                    name="phone",
                    field=models.CharField(blank=True, max_length=50),
                ),
            ],
        ),
    ]
