# Generated by Django 5.1.15 on 2026-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0002_add_episode_type_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="guest",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
