# Generated by Django 5.1.15 on 2026-02-03 21:44
# Modified: made column additions idempotent to handle columns that may already
# exist in production (e.g. added manually before this migration ran).

from django.db import migrations, models

TABLE = "production_ledger_mediaasset"


def _column_exists(schema_editor, column):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, TABLE)
    return any(col.name == column for col in description)


def add_label_and_platform(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if not _column_exists(schema_editor, "label"):
            cursor.execute(
                "ALTER TABLE `%s` ADD COLUMN `label` VARCHAR(200) NOT NULL DEFAULT ''" % TABLE
            )
        if not _column_exists(schema_editor, "platform"):
            cursor.execute(
                "ALTER TABLE `%s` ADD COLUMN `platform` VARCHAR(30) NOT NULL DEFAULT ''" % TABLE
            )


def remove_label_and_platform(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if _column_exists(schema_editor, "label"):
            cursor.execute("ALTER TABLE `%s` DROP COLUMN `label`" % TABLE)
        if _column_exists(schema_editor, "platform"):
            cursor.execute("ALTER TABLE `%s` DROP COLUMN `platform`" % TABLE)


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0003_add_guest_contact_fields"),
    ]

    operations = [
        # Use SeparateDatabaseAndState so Django's migration state always reflects
        # the final model, while the actual DDL is handled by the RunPython above
        # (which skips columns that already exist in the database).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="mediaasset",
                    name="label",
                    field=models.CharField(
                        blank=True, help_text="Display name for this asset", max_length=200
                    ),
                ),
                migrations.AddField(
                    model_name="mediaasset",
                    name="platform",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("youtube", "YouTube"),
                            ("youtube_live", "YouTube Live"),
                            ("google_meet", "Google Meet"),
                            ("riverside", "Riverside.fm"),
                            ("streamyard", "StreamYard"),
                            ("zoom", "Zoom"),
                            ("podbean", "Podbean"),
                            ("buzzsprout", "Buzzsprout"),
                            ("transistor", "Transistor"),
                            ("spotify", "Spotify for Podcasters"),
                            ("apple_podcasts", "Apple Podcasts Connect"),
                            ("google_drive", "Google Drive"),
                            ("dropbox", "Dropbox"),
                            ("s3", "Amazon S3"),
                            ("other", "Other"),
                        ],
                        help_text="Source platform for external links",
                        max_length=30,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_label_and_platform, remove_label_and_platform),
            ],
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("external_link", "External Link"),
                    ("api_import", "API Import"),
                ],
                max_length=20,
            ),
        ),
    ]
