# Generated by Django 5.1.15 on 2026-02-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0003_add_guest_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="label",
            field=models.CharField(
                blank=True, help_text="Display name for this asset", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("youtube", "YouTube"),
                    ("youtube_live", "YouTube Live"),
                    ("google_meet", "Google Meet"),
                    ("riverside", "Riverside.fm"),
                    ("streamyard", "StreamYard"),
                    ("zoom", "Zoom"),
                    ("podbean", "Podbean"),
                    ("buzzsprout", "Buzzsprout"),
                    ("transistor", "Transistor"),
                    ("spotify", "Spotify for Podcasters"),
                    ("apple_podcasts", "Apple Podcasts Connect"),
                    ("google_drive", "Google Drive"),
                    ("dropbox", "Dropbox"),
                    ("s3", "Amazon S3"),
                    ("other", "Other"),
                ],
                help_text="Source platform for external links",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("external_link", "External Link"),
                    ("api_import", "API Import"),
                ],
                max_length=20,
            ),
        ),
    ]
