# Generated by Django 5.1.9 on 2026-07-09 22:12

import django.db.models.deletion
import production_ledger.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0004_add_media_platform_and_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="active_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment currently live in Control Room, shown on the second screen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="production_ledger.segment",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Show logo for the second-screen display and other branding",
                null=True,
                upload_to=production_ledger.models.show_branding_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="second_screen_background",
            field=models.ImageField(
                blank=True,
                help_text="Default full-screen background shown between segments on the second screen",
                null=True,
                upload_to=production_ledger.models.show_branding_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("youtube", "YouTube"),
                    ("vimeo", "Vimeo"),
                    ("google_drive", "Google Drive"),
                    ("dropbox", "Dropbox"),
                    ("s3", "Amazon S3"),
                    ("direct_url", "Direct URL"),
                ],
                help_text="Source platform for external links",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="Sponsor site or ad landing page — encoded into the second-screen QR code",
                        max_length=2000,
                    ),
                ),
                (
                    "ad_copy",
                    models.TextField(
                        blank=True,
                        help_text="Short read-copy or promo message for the segment sponsor card",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=production_ledger.models.sponsor_logo_upload_path,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive sponsors are hidden from segment pickers but kept for historical episodes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="production_ledger.show",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="segment",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="Sponsor to display on the second screen while this segment is live",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments",
                to="production_ledger.sponsor",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsor",
            index=models.Index(
                fields=["organization_uuid", "show"],
                name="production__organiz_4ea68d_idx",
            ),
        ),
    ]
