# Generated by Django 3.2.16 on 2026-04-16 22:21
# Modified to be idempotent: uses SeparateDatabaseAndState so CreateModel
# operations skip tables that already exist in the database.

from django.conf import settings
from django.apps import apps as global_apps
from django.db import migrations, models
import django.db.models.deletion
import uuid


def _table_exists(schema_editor, table_name):
    return table_name in schema_editor.connection.introspection.table_names()


def create_models_if_not_exist(apps, schema_editor):
    invitation_exists = _table_exists(schema_editor, 'production_ledger_invitation')
    access_request_exists = _table_exists(schema_editor, 'production_ledger_accessrequest')

    if not invitation_exists:
        try:
            Invitation = apps.get_model('production_ledger', 'Invitation')
        except LookupError:
            Invitation = global_apps.get_model('production_ledger', 'Invitation')
        schema_editor.create_model(Invitation)

    if not access_request_exists:
        try:
            AccessRequest = apps.get_model('production_ledger', 'AccessRequest')
        except LookupError:
            AccessRequest = global_apps.get_model('production_ledger', 'AccessRequest')
        schema_editor.create_model(AccessRequest)


def drop_models_if_exist(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if _table_exists(schema_editor, 'production_ledger_accessrequest'):
            cursor.execute("DROP TABLE `production_ledger_accessrequest`")
        if _table_exists(schema_editor, 'production_ledger_invitation'):
            cursor.execute("DROP TABLE `production_ledger_invitation`")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_ledger', '0005_drop_episode_type_old'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='mediaasset',
                    name='platform',
                    field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('s3', 'Amazon S3'), ('direct_url', 'Direct URL')], help_text='Source platform for external links', max_length=30),
                ),
                migrations.CreateModel(
                    name='Invitation',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('email', models.EmailField(max_length=254)),
                        ('name', models.CharField(blank=True, default='', max_length=200)),
                        ('role', models.CharField(choices=[('admin', 'Admin'), ('host', 'Host'), ('producer', 'Producer'), ('editor', 'Editor'), ('guest', 'Guest')], default='guest', max_length=20)),
                        ('token', models.CharField(editable=False, max_length=64, unique=True)),
                        ('accepted_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Invitation',
                        'verbose_name_plural': 'Invitations',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='AccessRequest',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('name', models.CharField(max_length=200)),
                        ('email', models.EmailField(max_length=254)),
                        ('organization', models.CharField(blank=True, default='', max_length=200)),
                        ('message', models.TextField(blank=True, default='')),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                        ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Access Request',
                        'verbose_name_plural': 'Access Requests',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[
                migrations.AlterField(
                    model_name='mediaasset',
                    name='platform',
                    field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('s3', 'Amazon S3'), ('direct_url', 'Direct URL')], help_text='Source platform for external links', max_length=30),
                ),
                migrations.RunPython(create_models_if_not_exist, reverse_code=drop_models_if_exist),
            ],
        ),
    ]
