# Generated by Django 5.1.9 on 2026-07-09 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0005_episode_active_segment_show_logo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True)),
                ("timebox_minutes", models.PositiveIntegerField(default=5)),
                (
                    "owner_role",
                    models.CharField(
                        choices=[("host", "Host"), ("producer", "Producer")],
                        default="host",
                        max_length=20,
                    ),
                ),
                (
                    "bullet_prompts",
                    models.TextField(
                        blank=True, help_text="Bullet points for this segment"
                    ),
                ),
                (
                    "key_questions",
                    models.TextField(blank=True, help_text="Key questions to cover"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates are hidden from pickers but kept for history",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_templates",
                        to="production_ledger.show",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default sponsor to carry over when this template is used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segment_templates",
                        to="production_ledger.sponsor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment Template",
                "verbose_name_plural": "Segment Templates",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="segment",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this segment was copied from, if any — for reference only, not kept in sync",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments_created",
                to="production_ledger.segmenttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="segmenttemplate",
            index=models.Index(
                fields=["organization_uuid", "show"],
                name="production__organiz_a72a78_idx",
            ),
        ),
    ]
