# Generated by Django 5.1.9 on 2026-07-14 18:00

import production_ledger.models
from django.db import migrations, models


def unique_tokens_for_existing_episodes(apps, schema_editor):
    """AddField's callable default is evaluated once, so every pre-existing
    episode is backfilled with the SAME token. Reissue a distinct token per
    row so old episodes don't share one overlay link."""
    Episode = apps.get_model("production_ledger", "Episode")
    for episode in Episode.objects.all().iterator():
        episode.overlay_token = production_ledger.models.generate_overlay_token()
        episode.save(update_fields=["overlay_token"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0006_segmenttemplate_segment_source_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="overlay_token",
            field=models.CharField(
                db_index=True,
                default=production_ledger.models.generate_overlay_token,
                help_text="Token authorizing the no-login OBS overlay URL for this episode",
                max_length=64,
            ),
        ),
        migrations.RunPython(unique_tokens_for_existing_episodes, noop_reverse),
    ]
