# Generated by Django 3.2.16 on 2026-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_ledger', '0007_fix_icon_column_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this segment was marked complete', null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Marked complete during live recording'),
        ),
        migrations.AddField(
            model_name='segment',
            name='live_notes',
            field=models.TextField(blank=True, help_text='Notes captured during live recording of this segment'),
        ),
    ]
