# Generated by Django 3.2.16 on 2026-04-24 16:44
# Modified to be idempotent when columns were added outside migrations.

from django.db import migrations, models


TABLE = "production_ledger_segment"


def _column_exists(cursor, column_name):
    cursor.execute(
        "SELECT COUNT(*) FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
        [TABLE, column_name],
    )
    return cursor.fetchone()[0] > 0


def add_live_recording_fields_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if not _column_exists(cursor, "completed_at"):
            cursor.execute(
                "ALTER TABLE `%s` ADD COLUMN `completed_at` DATETIME NULL" % TABLE
            )
        if not _column_exists(cursor, "is_completed"):
            cursor.execute(
                "ALTER TABLE `%s` ADD COLUMN `is_completed` TINYINT(1) NOT NULL DEFAULT 0" % TABLE
            )
        if not _column_exists(cursor, "live_notes"):
            cursor.execute(
                "ALTER TABLE `%s` ADD COLUMN `live_notes` LONGTEXT NOT NULL" % TABLE
            )


def remove_live_recording_fields_if_present(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if _column_exists(cursor, "live_notes"):
            cursor.execute("ALTER TABLE `%s` DROP COLUMN `live_notes`" % TABLE)
        if _column_exists(cursor, "is_completed"):
            cursor.execute("ALTER TABLE `%s` DROP COLUMN `is_completed`" % TABLE)
        if _column_exists(cursor, "completed_at"):
            cursor.execute("ALTER TABLE `%s` DROP COLUMN `completed_at`" % TABLE)


class Migration(migrations.Migration):

    dependencies = [
        ('production_ledger', '0007_fix_icon_column_charset'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='segment',
                    name='completed_at',
                    field=models.DateTimeField(blank=True, help_text='When this segment was marked complete', null=True),
                ),
                migrations.AddField(
                    model_name='segment',
                    name='is_completed',
                    field=models.BooleanField(default=False, help_text='Marked complete during live recording'),
                ),
                migrations.AddField(
                    model_name='segment',
                    name='live_notes',
                    field=models.TextField(blank=True, help_text='Notes captured during live recording of this segment'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_live_recording_fields_if_missing, remove_live_recording_fields_if_present),
            ],
        ),
    ]
