# Generated by Django 3.2.16 on 2026-05-06 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_ledger', '0009_show_join_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_uuid', models.UUIDField(db_index=True, help_text='Organization UUID for multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('apple', 'Apple Podcasts'), ('spotify', 'Spotify'), ('amazon', 'Amazon Music / Audible'), ('google', 'Google Podcasts'), ('iheart', 'iHeartRadio'), ('stitcher', 'Stitcher'), ('pocket_casts', 'Pocket Casts'), ('overcast', 'Overcast'), ('castbox', 'Castbox'), ('rss', 'RSS Feed')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('live', 'Live'), ('failed', 'Failed'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('audio_spaces_key', models.CharField(blank=True, help_text='DO Spaces key for the episode audio file', max_length=500)),
                ('audio_public_url', models.URLField(blank=True, help_text='Public URL of the episode audio on DO Spaces / CDN')),
                ('audio_file_size', models.BigIntegerField(blank=True, help_text='Audio file size in bytes', null=True)),
                ('audio_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_content_type', models.CharField(default='audio/mpeg', max_length=50)),
                ('platform_episode_id', models.CharField(blank=True, max_length=255)),
                ('platform_url', models.URLField(blank=True, help_text='URL of this episode on the platform once live')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('went_live_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Podcast Distribution',
                'verbose_name_plural': 'Podcast Distributions',
            },
        ),
        migrations.CreateModel(
            name='PodcastFeedConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_uuid', models.UUIDField(db_index=True, help_text='Organization UUID for multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_title', models.CharField(blank=True, help_text='Podcast title (defaults to show name)', max_length=255)),
                ('feed_description', models.TextField(blank=True, help_text='Podcast description / summary')),
                ('feed_language', models.CharField(default='en', help_text="BCP-47 language code, e.g. 'en'", max_length=10)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(default='Technology', help_text='iTunes top-level category', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('explicit', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True)),
                ('cover_art_url', models.URLField(blank=True, help_text='Podcast cover art (min 1400×1400 px, max 3000×3000 px)')),
                ('feed_spaces_key', models.CharField(blank=True, help_text='Key/path within the DO Spaces bucket', max_length=500)),
                ('feed_public_url', models.URLField(blank=True, help_text='Public CDN URL of the RSS feed XML')),
                ('feed_last_built', models.DateTimeField(blank=True, help_text='When the feed was last re-built and uploaded', null=True)),
            ],
            options={
                'verbose_name': 'Podcast Feed Config',
                'verbose_name_plural': 'Podcast Feed Configs',
            },
        ),
        migrations.CreateModel(
            name='VideoShort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_uuid', models.UUIDField(db_index=True, help_text='Organization UUID for multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, help_text='Platform caption / description for the short')),
                ('hashtags', models.JSONField(blank=True, default=list, help_text='List of hashtag strings')),
                ('start_ms', models.PositiveIntegerField(help_text='Start time in milliseconds')),
                ('end_ms', models.PositiveIntegerField(help_text='End time in milliseconds')),
                ('aspect_ratio', models.CharField(choices=[('9:16', 'Vertical (9:16) — TikTok / Reels / Shorts'), ('1:1', 'Square (1:1) — Instagram / Twitter'), ('16:9', 'Horizontal (16:9) — YouTube Clip')], default='9:16', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('uploading', 'Uploading'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('spaces_key', models.CharField(blank=True, help_text='DO Spaces key for the rendered video', max_length=500)),
                ('public_url', models.URLField(blank=True, help_text='Public CDN URL of the rendered short')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('render_started_at', models.DateTimeField(blank=True, null=True)),
                ('render_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video Short',
                'verbose_name_plural': 'Video Shorts',
                'ordering': ['start_ms'],
            },
        ),
        migrations.RemoveIndex(
            model_name='showjoinrequest',
            name='production__show_id_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='showjoinrequest',
            name='production__user_id_status_idx',
        ),
        migrations.AddIndex(
            model_name='showjoinrequest',
            index=models.Index(fields=['show', 'status'], name='production__show_id_822fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='showjoinrequest',
            index=models.Index(fields=['user', 'status'], name='production__user_id_e6e8b9_idx'),
        ),
        migrations.AddField(
            model_name='videoshort',
            name='ai_caption_artifact',
            field=models.ForeignKey(blank=True, help_text='AI artifact that generated the caption/hashtags', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_shorts', to='production_ledger.aiartifact'),
        ),
        migrations.AddField(
            model_name='videoshort',
            name='clip_moment',
            field=models.ForeignKey(blank=True, help_text='Source clip moment this short was rendered from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_shorts', to='production_ledger.clipmoment'),
        ),
        migrations.AddField(
            model_name='videoshort',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videoshort_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoshort',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_shorts', to='production_ledger.episode'),
        ),
        migrations.AddField(
            model_name='videoshort',
            name='source_media_asset',
            field=models.ForeignKey(blank=True, help_text='Source media asset used for rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_shorts', to='production_ledger.mediaasset'),
        ),
        migrations.AddField(
            model_name='videoshort',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videoshort_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastfeedconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcastfeedconfig_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastfeedconfig',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_feed_config', to='production_ledger.show'),
        ),
        migrations.AddField(
            model_name='podcastfeedconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcastfeedconfig_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastdistribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcastdistribution_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastdistribution',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='production_ledger.episode'),
        ),
        migrations.AddField(
            model_name='podcastdistribution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcastdistribution_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='videoshort',
            index=models.Index(fields=['organization_uuid', 'episode'], name='production__organiz_33efc1_idx'),
        ),
        migrations.AddIndex(
            model_name='videoshort',
            index=models.Index(fields=['organization_uuid', 'status'], name='production__organiz_99754e_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastdistribution',
            index=models.Index(fields=['organization_uuid', 'episode'], name='production__organiz_63cda4_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastdistribution',
            index=models.Index(fields=['organization_uuid', 'platform', 'status'], name='production__organiz_40e0a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='podcastdistribution',
            unique_together={('episode', 'platform')},
        ),
    ]
