# Generated by Django 3.2.16 on 2026-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_ledger', '0010_distribution_transcription_shorts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiartifact',
            name='artifact_type',
            field=models.CharField(choices=[('questions', 'Questions'), ('show_notes', 'Show Notes'), ('segment_suggestions', 'Segment Suggestions'), ('social_posts', 'Social Posts'), ('titles', 'Titles'), ('chapters', 'Chapters'), ('shorts', 'Shorts')], max_length=30),
        ),
    ]
