# Generated by Django 5.1.15 on 2026-07-23 03:41

import django.db.models.deletion
import production_ledger.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0019_merge_splice_migrations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True)),
                ("timebox_minutes", models.PositiveIntegerField(default=5)),
                (
                    "owner_role",
                    models.CharField(
                        choices=[("host", "Host"), ("producer", "Producer")],
                        default="host",
                        max_length=20,
                    ),
                ),
                (
                    "bullet_prompts",
                    models.TextField(
                        blank=True, help_text="Bullet points for this segment"
                    ),
                ),
                (
                    "key_questions",
                    models.TextField(blank=True, help_text="Key questions to cover"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates are hidden from pickers but kept for history",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment Template",
                "verbose_name_plural": "Segment Templates",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="Sponsor site or ad landing page — encoded into the second-screen QR code",
                        max_length=2000,
                    ),
                ),
                (
                    "ad_copy",
                    models.TextField(
                        blank=True,
                        help_text="Short read-copy or promo message for the segment sponsor card",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive sponsors are hidden from segment pickers but kept for historical episodes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="platformcomment",
            new_name="production__platfor_6c56dc_idx",
            old_name="pl_comment_platform_extid",
        ),
        migrations.RenameIndex(
            model_name="platformcomment",
            new_name="production__organiz_0f7c07_idx",
            old_name="pl_comment_org_status",
        ),
        migrations.RenameIndex(
            model_name="platformcomment",
            new_name="production__episode_950d67_idx",
            old_name="pl_comment_ep_platform",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="live_notes",
        ),
        migrations.AddField(
            model_name="episode",
            name="active_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment currently live in Control Room, shown on the second screen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="production_ledger.segment",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="overlay_token",
            field=models.CharField(
                db_index=True,
                default=production_ledger.models.generate_overlay_token,
                help_text="Token authorizing the no-login OBS overlay URL for this episode",
                max_length=64,
            ),
        ),
        # OrgAPIKey table and indexes are already created in 0016_orgapikey
        # Skipping redundant operations here
        migrations.AddField(
            model_name="segmenttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segmenttemplate",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segment_templates",
                to="production_ledger.show",
            ),
        ),
        migrations.AddField(
            model_name="segmenttemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this segment was copied from, if any — for reference only, not kept in sync",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments_created",
                to="production_ledger.segmenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsors",
                to="production_ledger.show",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segmenttemplate",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="Default sponsor to carry over when this template is used",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segment_templates",
                to="production_ledger.sponsor",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="Sponsor to display on the second screen while this segment is live",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments",
                to="production_ledger.sponsor",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsor",
            index=models.Index(
                fields=["organization_uuid", "show"],
                name="production__organiz_4ea68d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segmenttemplate",
            index=models.Index(
                fields=["organization_uuid", "show"],
                name="production__organiz_a72a78_idx",
            ),
        ),
    ]
