# Generated by Django 5.1.15 on 2026-07-23 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0020_segmenttemplate_sponsor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orgapikey",
            index=models.Index(
                fields=["organization_uuid", "service"],
                name="production__organiz_6459bb_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="orgapikey",
            table=None,
        ),
    ]
