"""
AI Service Layer for Production Ledger.

Provider-agnostic interface for AI-assisted content generation.
All AI outputs are stored as AIArtifact objects with full provenance,
requiring explicit approval before being used in final content.

Configuration via environment variables:
- AI_PROVIDER: Provider name (mock, openai, anthropic, etc.)
- AI_API_KEY: API key for the provider
- AI_MODEL: Model identifier to use
"""
import json
import os
from abc import ABC, abstractmethod
from typing import Optional

from django.conf import settings
from django.utils import timezone

from ..constants import ApprovalStatus, ArtifactType
from ..models import AIArtifact, ClipMoment, Episode, Transcript


# =============================================================================
# CONFIGURATION
# =============================================================================

def get_ai_config():
    """Get AI configuration from environment variables."""
    return {
        'provider': os.environ.get('AI_PROVIDER', 'mock'),
        'api_key': os.environ.get('AI_API_KEY', ''),
        'model': os.environ.get('AI_MODEL', 'mock-model-v1'),
        'temperature': float(os.environ.get('AI_TEMPERATURE', '0.7')),
        'max_tokens': int(os.environ.get('AI_MAX_TOKENS', '2000')),
    }


# =============================================================================
# PROVIDER INTERFACE
# =============================================================================

class AIProvider(ABC):
    """Abstract base class for AI providers."""
    
    def __init__(self, config: dict):
        self.config = config
        self.provider_name = config.get('provider', 'unknown')
        self.model = config.get('model', 'unknown')
    
    @abstractmethod
    def generate(self, prompt: str, context: str = '') -> str:
        """Generate text from a prompt."""
        pass
    
    def get_params(self) -> dict:
        """Get parameters used for generation."""
        return {
            'temperature': self.config.get('temperature', 0.7),
            'max_tokens': self.config.get('max_tokens', 2000),
        }


# =============================================================================
# MOCK PROVIDER (Default for MVP)
# =============================================================================

class MockAIProvider(AIProvider):
    """
    Mock AI provider for development and testing.
    Returns structured placeholder content that looks realistic.
    """
    
    def generate(self, prompt: str, context: str = '') -> str:
        """Generate mock AI response based on the prompt type."""
        prompt_lower = prompt.lower()
        
        if 'question' in prompt_lower:
            return self._generate_questions(context)
        elif 'show note' in prompt_lower or 'summary' in prompt_lower:
            return self._generate_show_notes(context)
        elif 'social' in prompt_lower or 'post' in prompt_lower:
            return self._generate_social_posts(context)
        elif 'title' in prompt_lower:
            return self._generate_titles(context)
        elif 'chapter' in prompt_lower:
            return self._generate_chapters(context)
        else:
            return f"[Mock AI Response]\n\nPrompt received: {prompt[:200]}...\n\nContext length: {len(context)} characters\n\nThis is a mock response. Configure AI_PROVIDER environment variable to use a real AI provider."
    
    def _generate_questions(self, context: str) -> str:
        return """## Interview Questions

### Opening
1. Can you tell us about your background and what led you to your current role?
2. What's the one thing you wish more people understood about your field?

### Main Discussion
3. What are the biggest challenges you're seeing in the industry right now?
4. How do you approach problem-solving when facing complex technical decisions?
5. What role do you see AI playing in your work over the next few years?

### Deep Dive
6. Can you walk us through a specific project or situation that shaped your thinking?
7. What advice would you give to someone just starting out in this space?

### Closing
8. What are you most excited about working on right now?
9. Where can our listeners find you and learn more about your work?

---
*[Generated by Mock AI Provider - Replace with real provider for production]*"""
    
    def _generate_show_notes(self, context: str) -> str:
        return """# Episode Show Notes

## Summary
In this episode, we explore the intersection of technology and human creativity. Our guest shares insights from their journey and discusses the future of their field.

## Key Topics Covered
- The evolution of the industry over the past decade
- Practical approaches to common challenges
- The balance between automation and human judgment
- Building sustainable practices in a fast-moving field

## Key Takeaways
1. **Start with the problem, not the technology** - Understanding the core issue leads to better solutions
2. **Iterate and learn** - Small experiments compound into major improvements
3. **Collaboration matters** - The best outcomes come from diverse perspectives

## Resources Mentioned
- [Resource 1](https://example.com)
- [Resource 2](https://example.com)

## Timestamps
- 00:00 - Introduction
- 05:00 - Guest background
- 15:00 - Main discussion
- 35:00 - Rapid fire questions
- 42:00 - Closing thoughts

---
*[Generated by Mock AI Provider - Replace with real provider for production]*"""
    
    def _generate_social_posts(self, context: str) -> str:
        return """## Social Media Posts

### LinkedIn Post
🎙️ New Episode Alert!

Just dropped a conversation that I think you'll find valuable. We dig into the real challenges practitioners face and share actionable insights you can apply today.

Key insight: "The best solutions come from understanding the problem deeply before jumping to technology."

Listen now: [Link]

#Podcast #Technology #Leadership

---

### Twitter/X Thread
🧵 Thread: Key takeaways from our latest episode

1/ We talked about how the industry is evolving and what it means for practitioners at every level.

2/ The biggest misconception? That more tools = better outcomes. Our guest argues the opposite.

3/ "Focus on the fundamentals. The flashy stuff is distracting."

4/ Three things to try this week:
- Audit your current workflow
- Identify one bottleneck
- Run a small experiment

5/ Full episode link in bio. Would love to hear your thoughts! 👇

---

### Instagram Caption
New episode is live! 🎧

We're tackling the questions everyone's been asking. Swipe for the key moments ➡️

Drop a 🔥 if you've experienced this challenge too.

Link in bio to listen.

---
*[Generated by Mock AI Provider - Replace with real provider for production]*"""
    
    def _generate_titles(self, context: str) -> str:
        return """## Episode Title Options

### Straightforward
1. "The Future of [Topic]: A Practitioner's Perspective"
2. "[Guest Name] on Building Better [Systems/Processes/Products]"

### Intriguing
3. "Why Everything You Know About [Topic] Is Wrong"
4. "The Hidden Cost of [Common Practice]"

### Action-Oriented
5. "How to [Achieve Outcome] Without [Common Obstacle]"
6. "The [Number]-Step Framework for [Desired Result]"

### Conversational
7. "[Guest Name]: 'We Need to Rethink [Topic]'"
8. "What Happens When [Scenario]?"

---
*[Generated by Mock AI Provider - Replace with real provider for production]*"""
    
    def _generate_chapters(self, context: str) -> str:
        return """## Chapter Markers

```json
[
    {"time": "00:00", "title": "Introduction & Welcome"},
    {"time": "02:30", "title": "Guest Introduction"},
    {"time": "05:00", "title": "Career Journey & Background"},
    {"time": "12:00", "title": "Current Projects & Focus"},
    {"time": "18:00", "title": "Industry Challenges"},
    {"time": "25:00", "title": "Practical Solutions"},
    {"time": "32:00", "title": "Future Outlook"},
    {"time": "38:00", "title": "Advice for Listeners"},
    {"time": "42:00", "title": "Where to Find the Guest"},
    {"time": "44:00", "title": "Closing Thoughts"}
]
```

---
*[Generated by Mock AI Provider - Replace with real provider for production]*"""


# =============================================================================
# PROVIDER REGISTRY
# =============================================================================

PROVIDERS = {
    'mock': MockAIProvider,
    # Add more providers here:
    # 'openai': OpenAIProvider,
    # 'anthropic': AnthropicProvider,
}


def get_provider(config: Optional[dict] = None) -> AIProvider:
    """
    Get the configured AI provider instance.
    
    Args:
        config: Optional config dict. If not provided, loads from environment.
    
    Returns:
        AIProvider instance
    """
    if config is None:
        config = get_ai_config()
    
    provider_name = config.get('provider', 'mock')
    provider_class = PROVIDERS.get(provider_name, MockAIProvider)
    
    return provider_class(config)


# =============================================================================
# AI ARTIFACT CREATION FUNCTIONS
# =============================================================================

def create_ai_artifact(
    episode: Episode,
    artifact_type: str,
    prompt: str,
    output: str,
    context_refs: dict,
    user,
    config: Optional[dict] = None,
) -> AIArtifact:
    """
    Create an AIArtifact with full provenance.
    
    Args:
        episode: The episode this artifact belongs to
        artifact_type: Type from ArtifactType choices
        prompt: The prompt sent to the AI
        output: The AI-generated output
        context_refs: References to input data (transcript_id, clip_ids, etc.)
        user: The user creating this artifact
        config: Optional AI config dict
    
    Returns:
        AIArtifact instance (saved)
    """
    if config is None:
        config = get_ai_config()
    
    artifact = AIArtifact.objects.create(
        episode=episode,
        organization_uuid=episode.organization_uuid,
        artifact_type=artifact_type,
        input_prompt=prompt,
        input_context_refs=context_refs,
        output_text=output,
        provider=config.get('provider', 'mock'),
        model=config.get('model', 'unknown'),
        params={
            'temperature': config.get('temperature', 0.7),
            'max_tokens': config.get('max_tokens', 2000),
        },
        approval_status=ApprovalStatus.PENDING,
        transparency_summary=f"Generated by {config.get('provider', 'mock')} using {config.get('model', 'unknown')}",
        created_by=user,
    )
    
    return artifact


# =============================================================================
# HIGH-LEVEL GENERATION FUNCTIONS
# =============================================================================

def generate_questions(
    episode: Episode,
    topic_prompt: str,
    user,
    transcript: Optional[Transcript] = None,
) -> AIArtifact:
    """
    Generate interview questions for an episode.
    
    Args:
        episode: The episode to generate questions for
        topic_prompt: Topic/focus for the questions
        user: The user requesting generation
        transcript: Optional transcript to use as context
    
    Returns:
        AIArtifact with generated questions
    """
    config = get_ai_config()
    provider = get_provider(config)
    
    # Build the prompt
    prompt = f"""Generate thoughtful interview questions for a podcast episode.

Episode: {episode.title}
Show: {episode.show.name}
Topic Focus: {topic_prompt}
Episode Type: {episode.get_episode_type_display()}
Target Duration: {episode.target_minutes} minutes
"""
    
    # Add guest context if available
    guests = episode.episode_guests.select_related('guest').all()
    if guests:
        prompt += "\n\nGuests:\n"
        for eg in guests:
            prompt += f"- {eg.guest.name}"
            if eg.guest.title:
                prompt += f", {eg.guest.title}"
            if eg.guest.org:
                prompt += f" at {eg.guest.org}"
            prompt += "\n"
            if eg.key_topics:
                prompt += f"  Key topics: {eg.key_topics}\n"
            if eg.no_go_topics:
                prompt += f"  Avoid: {eg.no_go_topics}\n"
    
    # Build context from transcript
    context = ""
    context_refs = {}
    
    if transcript:
        context = transcript.raw_text[:5000]  # Limit context size
        context_refs['transcript_id'] = str(transcript.id)
    
    prompt += f"\n\nPlease generate {10 if episode.target_minutes >= 45 else 5} questions that flow naturally, ranging from opening warmup to deeper exploration."
    
    # Generate
    output = provider.generate(prompt, context)
    
    # Create artifact
    return create_ai_artifact(
        episode=episode,
        artifact_type=ArtifactType.QUESTIONS,
        prompt=prompt,
        output=output,
        context_refs=context_refs,
        user=user,
        config=config,
    )


def generate_show_notes(
    episode: Episode,
    user,
    transcript: Optional[Transcript] = None,
    clips: Optional[list] = None,
) -> AIArtifact:
    """
    Generate show notes for an episode.
    
    Args:
        episode: The episode to generate notes for
        user: The user requesting generation
        transcript: Optional transcript to use as context
        clips: Optional list of ClipMoment objects
    
    Returns:
        AIArtifact with generated show notes
    """
    config = get_ai_config()
    provider = get_provider(config)
    
    # Build the prompt
    prompt = f"""Generate comprehensive show notes for a podcast episode.

Episode: {episode.title}
Show: {episode.show.name}
Episode Type: {episode.get_episode_type_display()}
"""
    
    # Add segments context
    segments = episode.segments.all().order_by('order')
    if segments:
        prompt += "\n\nSegments (Run of Show):\n"
        for seg in segments:
            prompt += f"- {seg.title} ({seg.timebox_minutes} min): {seg.purpose}\n"
    
    # Add guest context
    guests = episode.episode_guests.select_related('guest').all()
    if guests:
        prompt += "\n\nGuests:\n"
        for eg in guests:
            prompt += f"- {eg.guest.name}"
            if eg.guest.title and eg.guest.org:
                prompt += f", {eg.guest.title} at {eg.guest.org}"
            prompt += "\n"
    
    # Build context
    context = ""
    context_refs = {}
    
    if transcript:
        context = transcript.raw_text[:8000]
        context_refs['transcript_id'] = str(transcript.id)
    
    if clips:
        context_refs['clip_ids'] = [str(c.id) for c in clips]
        prompt += "\n\nHighlighted Moments:\n"
        for clip in clips[:10]:  # Limit to 10 clips
            prompt += f"- [{clip.start_formatted}] {clip.title}: {clip.hook}\n"
    
    prompt += "\n\nGenerate show notes including: summary, key topics, takeaways, resources mentioned, and timestamps."
    
    # Generate
    output = provider.generate(prompt, context)
    
    # Create artifact
    return create_ai_artifact(
        episode=episode,
        artifact_type=ArtifactType.SHOW_NOTES,
        prompt=prompt,
        output=output,
        context_refs=context_refs,
        user=user,
        config=config,
    )


def generate_social_posts(
    episode: Episode,
    user,
    show_notes_draft: Optional[str] = None,
) -> AIArtifact:
    """
    Generate social media posts for an episode.
    
    Args:
        episode: The episode to generate posts for
        user: The user requesting generation
        show_notes_draft: Optional show notes to use as context
    
    Returns:
        AIArtifact with generated social posts
    """
    config = get_ai_config()
    provider = get_provider(config)
    
    # Build the prompt
    prompt = f"""Generate social media posts to promote a podcast episode.

Episode: {episode.title}
Show: {episode.show.name}

Please generate posts for:
1. LinkedIn (professional, 1-2 paragraphs)
2. Twitter/X (thread format, 5-7 tweets)
3. Instagram (caption with emoji, call to action)
"""
    
    # Add guest context for tagging
    guests = episode.episode_guests.select_related('guest').all()
    if guests:
        prompt += "\n\nGuests to mention:\n"
        for eg in guests:
            g = eg.guest
            prompt += f"- {g.name}"
            if g.links and isinstance(g.links, dict):
                if g.links.get('twitter'):
                    prompt += f" (@{g.links['twitter']})"
                if g.links.get('linkedin'):
                    prompt += f" [LinkedIn: {g.links['linkedin']}]"
            prompt += "\n"
    
    # Build context
    context = show_notes_draft[:3000] if show_notes_draft else ""
    context_refs = {}
    
    if show_notes_draft:
        context_refs['show_notes_source'] = 'draft'
    
    # Generate
    output = provider.generate(prompt, context)
    
    # Create artifact
    return create_ai_artifact(
        episode=episode,
        artifact_type=ArtifactType.SOCIAL_POSTS,
        prompt=prompt,
        output=output,
        context_refs=context_refs,
        user=user,
        config=config,
    )


def generate_segment_suggestions(
    episode: Episode,
    user,
    topic_focus: str = '',
) -> AIArtifact:
    """
    Generate run-of-show segment suggestions.
    
    Args:
        episode: The episode to generate segments for
        user: The user requesting generation
        topic_focus: Optional topic focus
    
    Returns:
        AIArtifact with segment suggestions
    """
    config = get_ai_config()
    provider = get_provider(config)
    
    prompt = f"""Suggest a run-of-show segment structure for a podcast episode.

Episode: {episode.title}
Show: {episode.show.name}
Target Duration: {episode.target_minutes} minutes
Episode Type: {episode.get_episode_type_display()}
Recording Context: {episode.get_recording_context_display()}
"""
    
    if topic_focus:
        prompt += f"\nTopic Focus: {topic_focus}\n"
    
    guests = episode.episode_guests.select_related('guest').all()
    if guests:
        prompt += f"\nNumber of Guests: {guests.count()}\n"
    
    prompt += """
Please suggest segments with:
- Order number
- Title
- Purpose
- Suggested duration (minutes)
- Key questions or prompts
- Who should lead (host or producer)

Format as a structured list."""
    
    output = provider.generate(prompt, "")
    
    return create_ai_artifact(
        episode=episode,
        artifact_type=ArtifactType.SEGMENT_SUGGESTIONS,
        prompt=prompt,
        output=output,
        context_refs={},
        user=user,
        config=config,
    )


def generate_titles(
    episode: Episode,
    user,
    transcript: Optional[Transcript] = None,
) -> AIArtifact:
    """
    Generate title options for an episode.
    
    Args:
        episode: The episode to generate titles for
        user: The user requesting generation
        transcript: Optional transcript for context
    
    Returns:
        AIArtifact with title suggestions
    """
    config = get_ai_config()
    provider = get_provider(config)
    
    prompt = f"""Generate compelling title options for a podcast episode.

Current Title: {episode.title}
Show: {episode.show.name}
Episode Type: {episode.get_episode_type_display()}
"""
    
    guests = episode.episode_guests.select_related('guest').all()
    if guests:
        guest_names = [eg.guest.name for eg in guests]
        prompt += f"\nGuests: {', '.join(guest_names)}\n"
    
    prompt += """
Please generate 6-8 title options in different styles:
- Straightforward/descriptive
- Intriguing/curiosity-driven  
- Action-oriented
- Quote-based (if applicable)"""
    
    context = ""
    context_refs = {}
    
    if transcript:
        context = transcript.raw_text[:3000]
        context_refs['transcript_id'] = str(transcript.id)
    
    output = provider.generate(prompt, context)
    
    return create_ai_artifact(
        episode=episode,
        artifact_type=ArtifactType.TITLES,
        prompt=prompt,
        output=output,
        context_refs=context_refs,
        user=user,
        config=config,
    )


def generate_chapters(
    episode: Episode,
    user,
    transcript: Optional[Transcript] = None,
) -> AIArtifact:
    """
    Generate chapter markers for an episode.
    
    Args:
        episode: The episode to generate chapters for
        user: The user requesting generation
        transcript: Optional transcript for context
    
    Returns:
        AIArtifact with chapter markers
    """
    config = get_ai_config()
    provider = get_provider(config)
    
    prompt = f"""Generate chapter markers for a podcast episode.

Episode: {episode.title}
Show: {episode.show.name}
Target Duration: {episode.target_minutes} minutes
"""
    
    segments = episode.segments.all().order_by('order')
    if segments:
        prompt += "\n\nRun of Show Segments:\n"
        for seg in segments:
            prompt += f"- {seg.title} ({seg.timebox_minutes} min)\n"
    
    prompt += """
Generate chapter markers in JSON format:
[{"time": "00:00", "title": "Chapter Title"}, ...]

Aim for chapters every 3-5 minutes of content."""
    
    context = ""
    context_refs = {}
    
    if transcript:
        context = transcript.raw_text[:5000]
        context_refs['transcript_id'] = str(transcript.id)
    
    output = provider.generate(prompt, context)
    
    return create_ai_artifact(
        episode=episode,
        artifact_type=ArtifactType.CHAPTERS,
        prompt=prompt,
        output=output,
        context_refs=context_refs,
        user=user,
        config=config,
    )
