# Generated by Django 5.1.9 on 2026-07-22 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production_ledger", "0008_add_segment_live_recording_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frame_rate",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Project frame rate (23.976, 24, 25, 29.97, 30, 50, 59.94, 60)",
                    ),
                ),
                ("canvas_width", models.PositiveIntegerField(default=1920)),
                ("canvas_height", models.PositiveIntegerField(default=1080)),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[
                            ("16:9", "16:9 (Landscape)"),
                            ("9:16", "9:16 (Vertical)"),
                            ("1:1", "1:1 (Square)"),
                            ("4:3", "4:3 (Standard)"),
                        ],
                        default="16:9",
                        max_length=10,
                    ),
                ),
                (
                    "timeline_duration_ms",
                    models.PositiveIntegerField(
                        default=3600000,
                        help_text="Total project duration in milliseconds",
                    ),
                ),
                ("autosave_enabled", models.BooleanField(default=True)),
                ("current_revision", models.PositiveIntegerField(default=0)),
                ("last_autosave_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        help_text="Episode being edited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_projects",
                        to="production_ledger.episode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor Project",
                "verbose_name_plural": "Editor Projects",
            },
        ),
        migrations.CreateModel(
            name="EditorNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "timeline_position_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Optional reference timestamp", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="splice.editorproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor Note",
                "verbose_name_plural": "Editor Notes",
            },
        ),
        migrations.CreateModel(
            name="EditorMarker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timeline_position_ms", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=255)),
                (
                    "color",
                    models.CharField(
                        default="#FF0000", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="splice.editorproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor Marker",
                "verbose_name_plural": "Editor Markers",
            },
        ),
        migrations.CreateModel(
            name="EditOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveIntegerField(
                        help_text="Project revision after this op"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("split_clip", "Split clip"),
                            ("trim_clip", "Trim clip"),
                            ("exclude_range", "Exclude range (ripple)"),
                            ("restore_range", "Restore excluded range"),
                            ("move_clip", "Move clip"),
                            ("set_audio_gain", "Set audio gain"),
                            ("set_audio_fade", "Set audio fade"),
                            ("mute_audio", "Mute/unmute audio"),
                            ("disable_video", "Disable/enable video"),
                            ("insert_asset", "Insert asset"),
                            ("remove_asset", "Remove asset"),
                            ("set_camera_angle", "Set camera angle"),
                            ("add_camera_cut", "Add camera cut"),
                            ("remove_camera_cut", "Remove camera cut"),
                            ("add_overlay", "Add overlay"),
                            ("update_overlay", "Update overlay"),
                            ("remove_overlay", "Remove overlay"),
                            ("add_caption", "Add caption"),
                            ("update_caption", "Update caption"),
                            ("remove_caption", "Remove caption"),
                            ("add_marker", "Add marker"),
                            ("delete_marker", "Delete marker"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(help_text="Operation parameters")),
                (
                    "inverse_operation",
                    models.JSONField(
                        blank=True,
                        help_text="Data needed to undo this operation",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "User action"),
                            ("transcript", "Transcript edit"),
                            ("speaker_detection", "Speaker detection"),
                            ("ai_suggestion", "AI suggestion"),
                            ("import", "Imported from file"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "applied",
                    models.BooleanField(default=True, help_text="False if undone"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_operation",
                    models.ForeignKey(
                        blank=True,
                        help_text="For batched/dependent operations",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_operations",
                        to="splice.editoperation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="splice.editorproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edit Operation",
                "verbose_name_plural": "Edit Operations",
            },
        ),
        migrations.CreateModel(
            name="CaptionCue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timeline_start_ms", models.PositiveIntegerField()),
                ("timeline_end_ms", models.PositiveIntegerField()),
                ("text", models.TextField(help_text="Caption text (UTF-8)")),
                ("speaker", models.CharField(blank=True, max_length=255, null=True)),
                ("auto_generated", models.BooleanField(default=False)),
                (
                    "burned_in",
                    models.BooleanField(
                        default=False, help_text="Include in video export"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captions",
                        to="splice.editorproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caption Cue",
                "verbose_name_plural": "Caption Cues",
            },
        ),
        migrations.CreateModel(
            name="CameraCut",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timeline_start_ms", models.PositiveIntegerField()),
                ("timeline_end_ms", models.PositiveIntegerField()),
                ("selected_camera_uuid", models.UUIDField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually set"),
                            ("automatic", "Auto-detected"),
                            ("suggestion", "AI suggestion"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="0.0-1.0 for automatic/suggestion cuts",
                        null=True,
                    ),
                ),
                (
                    "user_override",
                    models.BooleanField(
                        default=False,
                        help_text="User manually changed an automatic cut",
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        help_text="Project revision when created"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camera_cuts",
                        to="splice.editorproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera Cut",
                "verbose_name_plural": "Camera Cuts",
            },
        ),
        migrations.CreateModel(
            name="AudioTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "index",
                    models.PositiveIntegerField(help_text="Track order (0 = primary)"),
                ),
                ("name", models.CharField(default="Audio", max_length=255)),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Include in mix"),
                ),
                ("muted", models.BooleanField(default=False)),
                (
                    "volume_db",
                    models.FloatField(
                        default=0.0, help_text="Gain in dB (-inf to +12)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_tracks",
                        to="splice.editorproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio Track",
                "verbose_name_plural": "Audio Tracks",
            },
        ),
        migrations.CreateModel(
            name="AISuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("camera_cut", "Camera cut"),
                            ("caption", "Caption"),
                            ("silence_cut", "Silence removal"),
                            ("filler_phrase", "Filler phrase"),
                            ("speaker_label", "Speaker label"),
                        ],
                        max_length=50,
                    ),
                ),
                ("suggestion_data", models.JSONField(help_text="Proposed edit data")),
                ("confidence", models.FloatField(help_text="0.0-1.0 confidence score")),
                ("accepted", models.BooleanField(default=False)),
                ("rejected", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("ai_provider", models.CharField(blank=True, max_length=100)),
                ("ai_model", models.CharField(blank=True, max_length=100)),
                ("prompt_template", models.CharField(blank=True, max_length=255)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="splice.editorproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Suggestion",
                "verbose_name_plural": "AI Suggestions",
            },
        ),
        migrations.CreateModel(
            name="ExportPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Full Podcast 1080p'", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "container",
                    models.CharField(
                        choices=[
                            ("mp4", "MP4"),
                            ("mov", "MOV"),
                            ("webm", "WebM"),
                            ("mkv", "Matroska"),
                        ],
                        default="mp4",
                        max_length=20,
                    ),
                ),
                (
                    "video_codec",
                    models.CharField(
                        choices=[
                            ("h264", "H.264/AVC"),
                            ("h265", "H.265/HEVC"),
                            ("vp9", "VP9"),
                        ],
                        default="h264",
                        max_length=20,
                    ),
                ),
                ("video_bitrate_kbps", models.PositiveIntegerField(default=5000)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("frame_rate", models.PositiveIntegerField(default=30)),
                (
                    "audio_codec",
                    models.CharField(
                        choices=[("aac", "AAC"), ("mp3", "MP3"), ("opus", "Opus")],
                        default="aac",
                        max_length=20,
                    ),
                ),
                ("audio_bitrate_kbps", models.PositiveIntegerField(default=128)),
                (
                    "audio_channels",
                    models.PositiveIntegerField(
                        choices=[(1, "Mono"), (2, "Stereo")], default=2
                    ),
                ),
                (
                    "loudness_preset",
                    models.CharField(
                        default="PODCAST_STEREO",
                        help_text="Loudness normalization profile",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_presets",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Preset",
                "verbose_name_plural": "Export Presets",
            },
        ),
        migrations.CreateModel(
            name="ExportedMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveIntegerField(
                        help_text="Project revision used for this export"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        help_text="Final rendered media file",
                        null=True,
                        upload_to="exports/%Y/%m/%d/",
                    ),
                ),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "export_preset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports",
                        to="splice.exportpreset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exported Media",
                "verbose_name_plural": "Exported Media",
            },
        ),
        migrations.CreateModel(
            name="GraphicOverlay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "overlay_type",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("lower_third", "Lower third"),
                            ("title", "Title card"),
                            ("background", "Background"),
                            ("watermark", "Watermark"),
                            ("image", "Full-screen image"),
                            ("graphic", "Custom graphic"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timeline_start_ms", models.PositiveIntegerField()),
                ("timeline_end_ms", models.PositiveIntegerField()),
                (
                    "text_content",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "position_x",
                    models.IntegerField(default=0, help_text="X position in pixels"),
                ),
                (
                    "position_y",
                    models.IntegerField(default=0, help_text="Y position in pixels"),
                ),
                ("width", models.PositiveIntegerField(help_text="Width in pixels")),
                ("height", models.PositiveIntegerField(help_text="Height in pixels")),
                ("opacity", models.FloatField(default=1.0, help_text="0.0-1.0")),
                ("z_index", models.IntegerField(default=0, help_text="Layer order")),
                ("fade_in_ms", models.PositiveIntegerField(default=0)),
                ("fade_out_ms", models.PositiveIntegerField(default=0)),
                (
                    "template_id",
                    models.CharField(
                        blank=True,
                        help_text="Template identifier for styling",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overlay_uses",
                        to="production_ledger.mediaasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overlays",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Graphic Overlay",
                "verbose_name_plural": "Graphic Overlays",
            },
        ),
        migrations.CreateModel(
            name="MediaProxy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proxy_type",
                    models.CharField(
                        choices=[
                            ("video", "Video proxy"),
                            ("audio", "Audio proxy"),
                            ("waveform", "Waveform data"),
                            ("thumbnails", "Thumbnail grid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Queued"),
                            ("processing", "In progress"),
                            ("ready", "Complete"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Proxy file (video/audio) or JSON (waveform)",
                        null=True,
                        upload_to="proxies/%Y/%m/%d/",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "quality_preset",
                    models.CharField(
                        default="720p",
                        help_text="Resolution or quality level",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxies",
                        to="production_ledger.mediaasset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Proxy",
                "verbose_name_plural": "Media Proxies",
            },
        ),
        migrations.CreateModel(
            name="MediaSyncPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset1_time_ms", models.PositiveIntegerField()),
                ("asset2_time_ms", models.PositiveIntegerField()),
                (
                    "sync_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manually entered"),
                            ("waveform", "Waveform correlation"),
                            ("timecode", "Embedded timecode"),
                            ("marker", "Shared clap/marker"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, help_text="0.0-1.0 for automatic methods", null=True
                    ),
                ),
                (
                    "asset1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_as_asset1",
                        to="production_ledger.mediaasset",
                    ),
                ),
                (
                    "asset2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_as_asset2",
                        to="production_ledger.mediaasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_points",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Sync Point",
                "verbose_name_plural": "Media Sync Points",
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("probe_media", "Probe media file"),
                            ("create_proxy_video", "Create video proxy"),
                            ("create_proxy_audio", "Create audio proxy"),
                            ("generate_waveform", "Generate waveform"),
                            ("generate_thumbnails", "Generate thumbnails"),
                            ("synchronize_media", "Synchronize media"),
                            ("render_video", "Render video"),
                            ("render_audio", "Render audio"),
                            ("render_social_clip", "Render social clip"),
                            ("generate_transcription", "Generate transcription"),
                            ("detect_speakers", "Detect speakers"),
                            ("suggest_camera_cuts", "Suggest camera cuts"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "In progress"),
                            ("completed", "Complete"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(help_text="Job parameters")),
                (
                    "output_data",
                    models.JSONField(blank=True, help_text="Job results", null=True),
                ),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editor_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="production_ledger.mediaasset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Job",
                "verbose_name_plural": "Processing Jobs",
            },
        ),
        migrations.CreateModel(
            name="ProjectRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_number", models.PositiveIntegerField()),
                ("operation_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Revision",
                "verbose_name_plural": "Project Revisions",
            },
        ),
        migrations.CreateModel(
            name="SocialClip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveIntegerField(
                        help_text="Project revision for render"
                    ),
                ),
                ("timeline_start_ms", models.PositiveIntegerField()),
                ("timeline_end_ms", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[
                            ("16:9", "16:9 Landscape"),
                            ("9:16", "9:16 Vertical"),
                            ("1:1", "1:1 Square"),
                        ],
                        default="16:9",
                        max_length=10,
                    ),
                ),
                (
                    "template_id",
                    models.CharField(
                        blank=True,
                        help_text="Layout template identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "export_status",
                    models.CharField(
                        choices=[
                            ("pending", "Not exported"),
                            ("ready", "Ready"),
                            ("failed", "Export failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_clips",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Clip",
                "verbose_name_plural": "Social Clips",
            },
        ),
        migrations.CreateModel(
            name="VideoTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="Track order (0 = primary/bottom)"
                    ),
                ),
                ("name", models.CharField(default="Video", max_length=255)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Include in preview/export"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, help_text="Show in timeline UI"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_tracks",
                        to="splice.editorproject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Track",
                "verbose_name_plural": "Video Tracks",
            },
        ),
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_start_ms",
                    models.PositiveIntegerField(help_text="Trim start in source"),
                ),
                (
                    "source_end_ms",
                    models.PositiveIntegerField(help_text="Trim end in source"),
                ),
                (
                    "timeline_start_ms",
                    models.PositiveIntegerField(help_text="When this clip plays"),
                ),
                (
                    "timeline_duration_ms",
                    models.PositiveIntegerField(help_text="How long it plays"),
                ),
                ("muted", models.BooleanField(default=False)),
                ("volume_db", models.FloatField(default=0.0)),
                ("fade_in_ms", models.PositiveIntegerField(default=0)),
                ("fade_out_ms", models.PositiveIntegerField(default=0)),
                (
                    "playback_rate",
                    models.FloatField(default=1.0, help_text="1.0 = normal speed"),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False, help_text="Hide but don't delete"
                    ),
                ),
                (
                    "excluded",
                    models.BooleanField(default=False, help_text="Ripple-edit removed"),
                ),
                (
                    "audio_track",
                    models.ForeignKey(
                        blank=True,
                        help_text="For audio clips; null for video",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="splice.audiotrack",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_clips",
                        to="production_ledger.mediaasset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        help_text="For video clips; null for audio",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="splice.videotrack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clip",
                "verbose_name_plural": "Clips",
            },
        ),
        migrations.CreateModel(
            name="AIProviderConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_uuid",
                    models.UUIDField(
                        db_index=True, help_text="Organization UUID for multi-tenancy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.UUIDField(help_text="Organization UUID for scoping"),
                ),
                ("provider_name", models.CharField(max_length=100)),
                (
                    "api_key",
                    models.CharField(help_text="Encrypted secret", max_length=1000),
                ),
                ("api_endpoint", models.URLField(blank=True, max_length=2000)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "capabilities",
                    models.JSONField(
                        default=list,
                        help_text="List of capabilities this provider supports",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider Configuration",
                "verbose_name_plural": "AI Provider Configurations",
                "indexes": [
                    models.Index(
                        fields=["organization", "enabled"],
                        name="splice_aipr_organiz_841cd6_idx",
                    )
                ],
                "unique_together": {("organization", "provider_name")},
            },
        ),
        migrations.AddIndex(
            model_name="editorproject",
            index=models.Index(
                fields=["organization_uuid", "episode"],
                name="splice_edit_organiz_4e8e75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="editornote",
            index=models.Index(
                fields=["project"], name="splice_edit_project_d6c5dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editormarker",
            index=models.Index(
                fields=["project", "timeline_position_ms"],
                name="splice_edit_project_fff86e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="editoperation",
            index=models.Index(
                fields=["project", "revision"], name="splice_edit_project_3ac7ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editoperation",
            index=models.Index(
                fields=["project", "applied"], name="splice_edit_project_ee1fbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="captioncue",
            index=models.Index(
                fields=["project", "timeline_start_ms"],
                name="splice_capt_project_430413_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cameracut",
            index=models.Index(
                fields=["project", "timeline_start_ms"],
                name="splice_came_project_aff095_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audiotrack",
            index=models.Index(
                fields=["project", "index"], name="splice_audi_project_62799b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="audiotrack",
            unique_together={("project", "index")},
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(
                fields=["project", "suggestion_type"],
                name="splice_aisu_project_26be10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(
                fields=["accepted"], name="splice_aisu_accepte_2ade0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportpreset",
            index=models.Index(
                fields=["project"], name="splice_expo_project_9ab126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportedmedia",
            index=models.Index(
                fields=["project", "revision"], name="splice_expo_project_628f5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportedmedia",
            index=models.Index(fields=["status"], name="splice_expo_status_da8fec_idx"),
        ),
        migrations.AddIndex(
            model_name="graphicoverlay",
            index=models.Index(
                fields=["project", "timeline_start_ms"],
                name="splice_grap_project_941511_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaproxy",
            index=models.Index(
                fields=["source_asset", "proxy_type"],
                name="splice_medi_source__d91a4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaproxy",
            index=models.Index(fields=["status"], name="splice_medi_status_edb8c9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mediaproxy",
            unique_together={("source_asset", "proxy_type")},
        ),
        migrations.AddIndex(
            model_name="mediasyncpoint",
            index=models.Index(
                fields=["project"], name="splice_medi_project_76c0e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediasyncpoint",
            unique_together={("asset1", "asset2")},
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["status"], name="splice_proc_status_17ce07_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["editor_project", "job_type"],
                name="splice_proc_editor__c475f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["media_asset"], name="splice_proc_media_a_d3fa66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectrevision",
            index=models.Index(
                fields=["project", "revision_number"],
                name="splice_proj_project_c098c2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectrevision",
            unique_together={("project", "revision_number")},
        ),
        migrations.AddIndex(
            model_name="socialclip",
            index=models.Index(
                fields=["project"], name="splice_soci_project_1b4557_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videotrack",
            index=models.Index(
                fields=["project", "index"], name="splice_vide_project_9a55b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videotrack",
            unique_together={("project", "index")},
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(
                fields=["track", "timeline_start_ms"],
                name="splice_clip_track_i_917b66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(
                fields=["audio_track", "timeline_start_ms"],
                name="splice_clip_audio_t_e5bfc9_idx",
            ),
        ),
    ]
