# Generated by Django 5.1.15 on 2026-07-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_ledger", "0020_segmenttemplate_sponsor_and_more"),
        ("splice", "0002_local_first_architecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localenginesession",
            name="local_engine",
            field=models.ForeignKey(
                help_text="Local engine this session connects to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="splice.localengineinstallation",
            ),
        ),
        migrations.AlterField(
            model_name="localprocessingjob",
            name="editor_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Editor project this job serves (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_processing_jobs",
                to="splice.editorproject",
            ),
        ),
        migrations.AlterField(
            model_name="localprocessingjob",
            name="local_engine",
            field=models.ForeignKey(
                help_text="Local engine processing this job",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_jobs",
                to="splice.localengineinstallation",
            ),
        ),
        migrations.AlterField(
            model_name="localprocessingjob",
            name="media_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Media asset this job processes (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_processing_jobs",
                to="production_ledger.mediaasset",
            ),
        ),
        migrations.AlterField(
            model_name="mediafingerprint",
            name="asset",
            field=models.OneToOneField(
                help_text="Media asset this fingerprint identifies",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fingerprint",
                to="production_ledger.mediaasset",
            ),
        ),
        migrations.AlterField(
            model_name="medialocation",
            name="asset",
            field=models.ForeignKey(
                help_text="Media asset this location refers to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="production_ledger.mediaasset",
            ),
        ),
        migrations.AlterField(
            model_name="renderplan",
            name="project",
            field=models.ForeignKey(
                help_text="Editor project this plan renders",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="render_plans",
                to="splice.editorproject",
            ),
        ),
    ]
